// Build config for simple-obsidian-calendar.
//
// Ported from obsidian-periodic-notes/esbuild.config.mjs with these changes:
//   - Entry point: src/main.ts only (styles.css is at the repo root and Obsidian
//     reads it directly; no esbuild processing needed for production)
//   - target: "es2018" (up from es2016, matches our tsconfig)
//   - outdir for dev: reads TEST_VAULT from .env (no REAL_VAULT switch — not needed)
//   - Plugin id comes from manifest.json as in the original
//   CHANGED: `assert { type: "json" }` → `with { type: "json" }` (Node ≥ 22 requires
//            the newer "import attributes" syntax; "assert" was removed).
//   CHANGED: esbuild 0.17+ removed `watch` from build() options. Dev mode now uses
//            context().watch() so the watch flag no longer causes a fatal build error.
//   CHANGED: CSS is not bundled through esbuild in production. styles.css lives at the
//            repo root and Obsidian loads it from there directly. In dev mode a simple
//            fs.copyFileSync copies it into the test vault alongside main.js.

import { config } from "dotenv";
import esbuild from "esbuild";
import process from "process";
import { copyFileSync, mkdirSync } from "fs";
import builtins from "builtin-modules";
import sveltePlugin from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";

// CHANGED: "with" replaces "assert" — required by Node 22+.
import manifest from "./manifest.json" with { type: "json" };

// Load .env so TEST_VAULT is available in dev mode.
config();

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// In dev mode, write directly into the Obsidian vault defined by TEST_VAULT in .env.
// In production, write to the repo root (Obsidian loads main.js and styles.css from there).
let outdir = "./";
if (!prod) {
  const vaultDir = process.env.TEST_VAULT;
  if (!vaultDir) {
    console.error(
      "\n[esbuild] ERROR: TEST_VAULT is not set. Create a .env file with:\n  TEST_VAULT=/path/to/your/vault/\n"
    );
    process.exit(1);
  }
  // Ensure trailing slash before appending plugin path.
  const base = vaultDir.endsWith("/") ? vaultDir : `${vaultDir}/`;
  outdir = `${base}.obsidian/plugins/${manifest.id}/`;
}

console.info(`\n[esbuild] Writing plugin to: ${outdir}\n`);

// CHANGED: JS-only build — Obsidian loads styles.css directly from the plugin dir.
// In dev we copy styles.css manually; in prod it already lives at the repo root.
const externalModules = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/closebrackets",
  "@codemirror/commands",
  "@codemirror/fold",
  "@codemirror/gutter",
  "@codemirror/history",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/matchbrackets",
  "@codemirror/rangeset",
  "@codemirror/rectangular-selection",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/stream-parser",
  "@codemirror/text",
  "@codemirror/view",
  ...builtins,
];

const jsBuildOptions = {
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: externalModules,
  format: "cjs",
  // CHANGED from original: target es2018 to match our tsconfig.json.
  target: "es2018",
  minify: prod,
  sourcemap: prod ? false : "inline",
  plugins: [
    sveltePlugin({
      // Inline component CSS into the JS bundle (no separate .css per component).
      compilerOptions: { css: "injected" },
      preprocess: sveltePreprocess(),
    }),
  ],
  logLevel: "info",
  treeShaking: true,
  // Output directly to the target dir as main.js (not src/main.js).
  outfile: `${outdir}main.js`,
};

if (prod) {
  // Production: build JS to repo root. styles.css is already at root — no copy needed.
  esbuild.build(jsBuildOptions).catch(() => process.exit(1));
} else {
  // Dev: ensure the vault plugin directory exists, then copy styles.css into it.
  mkdirSync(outdir, { recursive: true });
  copyFileSync("styles.css", `${outdir}styles.css`);
  console.info(`[esbuild] Copied styles.css → ${outdir}styles.css`);

  // CHANGED: esbuild 0.17+ removed `watch` from build() options.
  // Dev mode uses context().watch() per the new esbuild watch API.
  esbuild
    .context(jsBuildOptions)
    .then((ctx) => ctx.watch())
    .catch(() => process.exit(1));
}
