// Build config for simple-obsidian-calendar.
//
// Ported from obsidian-periodic-notes/esbuild.config.mjs with these changes:
//   - Entry points: src/main.ts + styles.css (styles.css sits at repo root, not src/)
//   - target: "es2018" (up from es2016, matches our tsconfig)
//   - outdir for dev: reads TEST_VAULT from .env (no REAL_VAULT switch — not needed)
//   - Plugin id comes from manifest.json as in the original

import { config } from "dotenv";
import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import sveltePlugin from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";

import manifest from "./manifest.json" assert { type: "json" };

// Load .env so TEST_VAULT is available in dev mode.
config();

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// In dev mode, write directly into the Obsidian vault defined by TEST_VAULT in .env.
// In production, write to the repo root (Obsidian loads main.js and styles.css from there).
let outdir = "./";
if (!prod) {
  const vaultDir = process.env.TEST_VAULT;
  if (!vaultDir) {
    console.error(
      "\n[esbuild] ERROR: TEST_VAULT is not set. Create a .env file with:\n  TEST_VAULT=/path/to/your/vault/\n"
    );
    process.exit(1);
  }
  // Ensure trailing slash before appending plugin path.
  const base = vaultDir.endsWith("/") ? vaultDir : `${vaultDir}/`;
  outdir = `${base}.obsidian/plugins/${manifest.id}/`;
}

console.info(`\n[esbuild] Writing plugin to: ${outdir}\n`);

esbuild
  .build({
    banner: { js: banner },
    // Source: plugin entry point + top-level stylesheet.
    entryPoints: ["src/main.ts", "styles.css"],
    bundle: true,
    // Mark Obsidian and all Electron/CodeMirror/Node packages as external —
    // they are provided by the Obsidian host at runtime and must not be bundled.
    external: [
      "obsidian",
      "electron",
      "@codemirror/autocomplete",
      "@codemirror/closebrackets",
      "@codemirror/commands",
      "@codemirror/fold",
      "@codemirror/gutter",
      "@codemirror/history",
      "@codemirror/language",
      "@codemirror/lint",
      "@codemirror/matchbrackets",
      "@codemirror/rangeset",
      "@codemirror/rectangular-selection",
      "@codemirror/search",
      "@codemirror/state",
      "@codemirror/stream-parser",
      "@codemirror/text",
      "@codemirror/view",
      ...builtins,
    ],
    format: "cjs",
    // CHANGED from original: target es2018 to match our tsconfig.json.
    target: "es2018",
    // Dev: watch + inline source maps for debugging. Prod: minify, no maps.
    minify: prod,
    sourcemap: prod ? false : "inline",
    // esbuild watch API changed in 0.17+: use context().watch() instead of build({watch}).
    // For simplicity we keep the old-style boolean and rely on esbuild-svelte's version support.
    watch: !prod,
    plugins: [
      sveltePlugin({
        // Inline component CSS into the JS bundle (no separate .css per component).
        compilerOptions: { css: "injected" },
        preprocess: sveltePreprocess(),
      }),
    ],
    logLevel: "info",
    treeShaking: true,
    outdir,
  })
  .catch(() => process.exit(1));
